---
# OpenVPN Role - Handlers

- name: restart openvpn
  systemd:
    name: openvpn
    state: restarted

- name: stop openvpn
  systemd:
    name: openvpn
    state: stopped

- name: start openvpn
  systemd:
    name: openvpn
    state: started

- name: save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4
  changed_when: false