---
# Vaultwarden Role - Variables

# Docker
docker_compose_version: "2.20.0"

# Vaultwarden
vaultwarden_image: "vaultwarden/server:{{ vaultwarden_version }}"
vaultwarden_container_name: "vaultwarden"

# Nginx
nginx_config_path: "/etc/nginx/sites-available/vaultwarden"
nginx_enabled_path: "/etc/nginx/sites-enabled/vaultwarden"

# Firewall
firewall_ports:
  - '22'
  - '80'
  - '443'

# SSL
certbot_packages:
  - certbot
  - python3-certbot-nginx