---
# n8n Role - Default Variables

# n8n
n8n_version: "latest"
n8n_port: 5678
n8n_protocol: "https"
n8n_data_dir: "/opt/n8n"
n8n_domain: "n8n.example.com"

# Basic Auth
n8n_basic_auth_user: "admin"
n8n_basic_auth_password: "change_me"

# Database
n8n_db_type: "postgres"
n8n_db_name: "n8n"
n8n_db_user: "n8n"
n8n_db_password: "change_me"
n8n_db_port: 5432

# SSL
n8n_ssl_enabled: true
n8n_ssl_email: "admin@example.com"

# Webhook
n8n_webhook_url: "https://{{ n8n_domain }}/webhook/"

# Timezone
n8n_timezone: "Asia/Jakarta"

# Generic Timezone
n8n_generic_timezone: "Asia/Jakarta"